# Generated by Django 6.0.3 on 2026-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='destino_origem',
            field=models.CharField(max_length=200),
        ),
    ]
