# Generated by Django 6.0.3 on 2026-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Compra', 'Compra de Fornecedor'), ('Devolucao', 'Devolução de Cliente'), ('Ajuste_Positivo', 'Ajuste de Inventário (+)'), ('Venda', 'Venda / Expedição'), ('Avaria', 'Perda / Avaria'), ('Consumo', 'Consumo Interno'), ('Ajuste_Negativo', 'Ajuste de Inventário (-)')], max_length=50, null=True),
        ),
    ]
